In [3]:
import numpy as np
import pandas as pd
from pprint import pprint
import math

In [207]:
data = pd.read_csv("resources/dataset_train.csv")
#data_test = pd.read_csv("resources/dataset_test.csv")

In [208]:
data.head(10)

Index Hogwarts House First Name   Last Name    Birthday Best Hand  \
0      0      Ravenclaw     Tamara         Hsu  2000-03-30      Left   
1      1      Slytherin      Erich     Paredes  1999-10-14     Right   
2      2      Ravenclaw   Stephany       Braun  1999-11-03      Left   
3      3     Gryffindor      Vesta   Mcmichael  2000-08-19      Left   
4      4     Gryffindor     Gaston       Gibbs  1998-09-27      Left   
5      5      Slytherin    Corrine     Hammond  1999-04-04     Right   
6      6     Gryffindor        Tom       Guido  2000-09-30      Left   
7      7     Hufflepuff     Alicia     Hayward  1997-07-08     Right   
8      8     Gryffindor      Bella  Leatherman  1998-12-07      Left   
9      9     Hufflepuff     Hayden      Aponte  2001-10-13     Right   

   Arithmancy   Astronomy  Herbology  Defense Against the Dark Arts  \
0     58384.0 -487.886086   5.727180                       4.878861   
1     67239.0 -552.060507  -5.987446                       5.520605   
2     23702.0 -366.076117   7.725017                       3.660761   
3     32667.0  697.742809  -6.497214                      -6.977428   
4     60158.0  436.775204  -7.820623                            NaN   
5     21209.0 -613.687160  -4.289197                       6.136872   
6     49167.0  628.046051  -4.861976                      -6.280461   
7     33010.0  411.412727   5.931832                      -4.114127   
8     20278.0  496.394945  -5.215891                      -4.963949   
9     46316.0  527.193585   7.922205                      -5.271936   

   Divination  Muggle Studies  Ancient Runes  History of Magic  \
0       4.722      272.035831     532.484226          5.231058   
1      -5.612     -487.340557     367.760303          4.107170   
2       6.140      664.893521     602.585284          3.555579   
3       4.026     -537.001128     523.982133         -4.809637   
4       2.236     -444.262537     599.324514         -3.444377   
5      -6.592     -440.997704     396.201804          5.380286   
6         NaN     -926.892512     583.742442         -7.322486   
7       2.769     -502.021336     439.351416               NaN   
8       5.855     -626.552041     567.842402         -6.198661   
9       3.356     -398.101991     341.475606          4.978614   

   Transfiguration    Potions  Care of Magical Creatures     Charms  Flying  
0      1039.788281   3.790369                   0.715939 -232.79405  -26.89  
1      1058.944592   7.248742                   0.091674 -252.18425 -113.45  
2      1088.088348   8.728531                  -0.515327 -227.34265   30.42  
3       920.391449   0.821911                  -0.014040 -256.84675  200.64  
4       937.434724   4.311066                  -0.264070 -256.38730  157.98  
5      1052.845164  11.751212                   1.049894 -247.94549  -34.69  
6       923.539573   1.646666                   0.153022 -257.83447  261.55  
7      1041.091935   6.581791                  -0.171704 -244.03492   72.25  
8       925.255500   1.086518                   1.147032 -252.27561  244.11  
9      1041.414665   2.068824                  -0.529579 -244.57527   -0.09

In [209]:
data.mean()

Index                              799.500000
Arithmancy                       49634.570243
Astronomy                           39.797131
Herbology                            1.141020
Defense Against the Dark Arts       -0.387863
Divination                           3.153910
Muggle Studies                    -224.589915
Ancient Runes                      495.747970
History of Magic                     2.963095
Transfiguration                   1030.096946
Potions                              5.950373
Care of Magical Creatures           -0.053427
Charms                            -243.374409
Flying                              21.958012
dtype: float64

In [210]:
data_clean = data.fillna(data_train.mean())
data_clean

Index Hogwarts House  First Name    Last Name    Birthday Best Hand  \
0         0      Ravenclaw      Tamara          Hsu  2000-03-30      Left   
1         1      Slytherin       Erich      Paredes  1999-10-14     Right   
2         2      Ravenclaw    Stephany        Braun  1999-11-03      Left   
3         3     Gryffindor       Vesta    Mcmichael  2000-08-19      Left   
4         4     Gryffindor      Gaston        Gibbs  1998-09-27      Left   
5         5      Slytherin     Corrine      Hammond  1999-04-04     Right   
6         6     Gryffindor         Tom        Guido  2000-09-30      Left   
7         7     Hufflepuff      Alicia      Hayward  1997-07-08     Right   
8         8     Gryffindor       Bella   Leatherman  1998-12-07      Left   
9         9     Hufflepuff      Hayden       Aponte  2001-10-13     Right   
10       10     Hufflepuff     Antonio      Denning  1998-05-21     Right   
11       11     Hufflepuff     Neville         Hall  2001-02-16      Left   
12       12     Hufflepuff       Rocky        Trask  2000-03-13     Right   
13       13      Slytherin        Fred        Simms  1997-02-27      Left   
14       14      Ravenclaw         Jan       Saylor  1998-03-16     Right   
15       15      Ravenclaw        Long        Burks  2001-10-03      Left   
16       16     Gryffindor        Fran    Jorgensen  1997-09-23      Left   
17       17     Gryffindor     Freddie         Ward  2001-05-31      Left   
18       18      Ravenclaw      Tyrone       Cooley  2000-03-09     Right   
19       19     Hufflepuff       Elden       Scholl  1999-04-18     Right   
20       20     Gryffindor         Mel       Marion  1998-12-20      Left   
21       21     Gryffindor       Pansy       Mosher  1999-12-15      Left   
22       22      Ravenclaw      Joseph      Coulter  2001-08-22      Left   
23       23     Hufflepuff       Rosie       Tuggle  1999-07-05      Left   
24       24      Ravenclaw      Esther           Li  2001-08-02      Left   
25       25     Hufflepuff       Lucio         Wray  1999-01-21      Left   
26       26      Slytherin     Araceli        Flint  1998-03-01      Left   
27       27     Hufflepuff  Georgianna       Wooten  2000-01-18     Right   
28       28     Gryffindor        Mimi        Baird  1997-05-22      Left   
29       29     Hufflepuff      Brandy       Andrus  2000-12-27     Right   
...     ...            ...         ...          ...         ...       ...   
1570   1570     Hufflepuff     Danette       Amaral  2000-08-18     Right   
1571   1571      Slytherin      Marcel     Pederson  2000-01-07      Left   
1572   1572     Hufflepuff       Vonda      Wingate  2001-07-25      Left   
1573   1573     Gryffindor     Ezekiel      Vallejo  1998-07-16     Right   
1574   1574      Ravenclaw        Jade        Trent  2000-03-08     Right   
1575   1575      Ravenclaw     Laverne       France  2000-10-22      Left   
1576   1576      Ravenclaw       April        Nason  1997-10-12      Left   
1577   1577      Ravenclaw    Germaine    Theriault  1999-12-16     Right   
1578   1578     Gryffindor       Ivory       Boykin  1998-12-01     Right   
1579   1579      Slytherin     Susanne         Linn  1998-09-09     Right   
1580   1580     Hufflepuff      Silvia      Landers  2001-05-06     Right   
1581   1581      Slytherin       Ramon        Crain  2000-05-11      Left   
1582   1582      Ravenclaw   Elizebeth         Wong  2000-08-07      Left   
1583   1583      Slytherin      Deanna      Dowdell  1998-11-07      Left   
1584   1584      Slytherin       Josef        Stoll  1997-09-14     Right   
1585   1585     Hufflepuff     Eduardo       Maness  1998-09-25      Left   
1586   1586      Slytherin        Earl    Mccloskey  1999-01-21      Left   
1587   1587     Hufflepuff     Juliana   Delgadillo  1999-07-21     Right   
1588   1588      Slytherin      Jessie       Tilley  1999-04-16     Right   
1589   1589     Hufflepuff      Dionne        Hynes  2001-06-24      Left   
15

### Liste des variables

In [211]:
column_names_list = list(data_clean.columns)
column_names_list

['Index',
 'Hogwarts House',
 'First Name',
 'Last Name',
 'Birthday',
 'Best Hand',
 'Arithmancy',
 'Astronomy',
 'Herbology',
 'Defense Against the Dark Arts',
 'Divination',
 'Muggle Studies',
 'Ancient Runes',
 'History of Magic',
 'Transfiguration',
 'Potions',
 'Care of Magical Creatures',
 'Charms',
 'Flying']

### Definir m

In [212]:
m = data_clean['Index'].shape[0]
m
type(m)

int

### Definir X 

In [198]:
# Add a column of ones in X
X0 = np.ones(m)
X0[:10]
X0.shape


(1600,)

In [213]:
X1 = list(data_clean['Best Hand'])
set(X1)

{'Left', 'Right'}

In [214]:

X1 = [0.0 if el == 'Left' else 1.0 for el in X1 ]
X1 = np.array(X1)
X1[:10]
set(X1)

{0.0, 1.0}

In [215]:
X2_15 = data_clean[column_names_list[6:19]]
X2_15[:10]

Arithmancy   Astronomy  Herbology  Defense Against the Dark Arts  \
0     58384.0 -487.886086   5.727180                       4.878861   
1     67239.0 -552.060507  -5.987446                       5.520605   
2     23702.0 -366.076117   7.725017                       3.660761   
3     32667.0  697.742809  -6.497214                      -6.977428   
4     60158.0  436.775204  -7.820623                      -0.387863   
5     21209.0 -613.687160  -4.289197                       6.136872   
6     49167.0  628.046051  -4.861976                      -6.280461   
7     33010.0  411.412727   5.931832                      -4.114127   
8     20278.0  496.394945  -5.215891                      -4.963949   
9     46316.0  527.193585   7.922205                      -5.271936   

   Divination  Muggle Studies  Ancient Runes  History of Magic  \
0     4.72200      272.035831     532.484226          5.231058   
1    -5.61200     -487.340557     367.760303          4.107170   
2     6.14000      664.893521     602.585284          3.555579   
3     4.02600     -537.001128     523.982133         -4.809637   
4     2.23600     -444.262537     599.324514         -3.444377   
5    -6.59200     -440.997704     396.201804          5.380286   
6     3.15391     -926.892512     583.742442         -7.322486   
7     2.76900     -502.021336     439.351416          2.963095   
8     5.85500     -626.552041     567.842402         -6.198661   
9     3.35600     -398.101991     341.475606          4.978614   

   Transfiguration    Potions  Care of Magical Creatures     Charms  Flying  
0      1039.788281   3.790369                   0.715939 -232.79405  -26.89  
1      1058.944592   7.248742                   0.091674 -252.18425 -113.45  
2      1088.088348   8.728531                  -0.515327 -227.34265   30.42  
3       920.391449   0.821911                  -0.014040 -256.84675  200.64  
4       937.434724   4.311066                  -0.264070 -256.38730  157.98  
5      1052.845164  11.751212                   1.049894 -247.94549  -34.69  
6       923.539573   1.646666                   0.153022 -257.83447  261.55  
7      1041.091935   6.581791                  -0.171704 -244.03492   72.25  
8       925.255500   1.086518                   1.147032 -252.27561  244.11  
9      1041.414665   2.068824                  -0.529579 -244.57527   -0.09

In [216]:
X2_15 = np.array(data_clean[column_names_list[6:19]])
X2_15[:10]


array([[ 5.83840000e+04, -4.87886086e+02,  5.72718030e+00,
         4.87886086e+00,  4.72200000e+00,  2.72035831e+02,
         5.32484226e+02,  5.23105829e+00,  1.03978828e+03,
         3.79036907e+00,  7.15939127e-01, -2.32794050e+02,
        -2.68900000e+01],
       [ 6.72390000e+04, -5.52060507e+02, -5.98744578e+00,
         5.52060507e+00, -5.61200000e+00, -4.87340557e+02,
         3.67760303e+02,  4.10717029e+00,  1.05894459e+03,
         7.24874198e+00,  9.16741839e-02, -2.52184250e+02,
        -1.13450000e+02],
       [ 2.37020000e+04, -3.66076117e+02,  7.72501661e+00,
         3.66076117e+00,  6.14000000e+00,  6.64893521e+02,
         6.02585284e+02,  3.55557900e+00,  1.08808835e+03,
         8.72853092e+00, -5.15326846e-01, -2.27342650e+02,
         3.04200000e+01],
       [ 3.26670000e+04,  6.97742809e+02, -6.49721444e+00,
        -6.97742809e+00,  4.02600000e+00, -5.37001128e+02,
         5.23982133e+02, -4.80963661e+00,  9.20391449e+02,
         8.21910501e-01, -1.40404172e

In [217]:
set(X2_15[:,1])

{25.86766088304921,
 39.797130890164766,
 49.84224410654053,
 91.14672493805624,
 93.57414148230595,
 93.52254735484192,
 102.42823027215802,
 106.0725568513047,
 108.831102524061,
 110.91990967978558,
 135.72156796666093,
 139.1462792576635,
 149.53328301056587,
 150.10579655246653,
 153.9488923822856,
 154.20995443727043,
 156.12316467691514,
 160.41647659977562,
 171.3773473386616,
 183.07434777484016,
 184.3132966036434,
 183.96007132741119,
 191.66200704041302,
 195.61265188910028,
 199.31091178563872,
 206.2341293390876,
 209.9412917917984,
 215.4958686986276,
 217.269672003478,
 220.8153067333725,
 222.82775706040024,
 225.06455284497338,
 227.437621017206,
 230.8769673873851,
 231.72561987599357,
 232.888776991508,
 232.20774160951626,
 230.74904783788315,
 232.12037505716359,
 236.8888790015881,
 236.8861914184944,
 237.51010129534126,
 239.69576421273362,
 239.5845457683503,
 239.1882792648753,
 240.08239229860507,
 240.55918719267208,
 245.17240578830203,
 248.21131415207023

In [218]:
X = np.c_[X0, X1, X2_15]
X[:3]

array([[ 1.00000000e+00,  0.00000000e+00,  5.83840000e+04,
        -4.87886086e+02,  5.72718030e+00,  4.87886086e+00,
         4.72200000e+00,  2.72035831e+02,  5.32484226e+02,
         5.23105829e+00,  1.03978828e+03,  3.79036907e+00,
         7.15939127e-01, -2.32794050e+02, -2.68900000e+01],
       [ 1.00000000e+00,  1.00000000e+00,  6.72390000e+04,
        -5.52060507e+02, -5.98744578e+00,  5.52060507e+00,
        -5.61200000e+00, -4.87340557e+02,  3.67760303e+02,
         4.10717029e+00,  1.05894459e+03,  7.24874198e+00,
         9.16741839e-02, -2.52184250e+02, -1.13450000e+02],
       [ 1.00000000e+00,  0.00000000e+00,  2.37020000e+04,
        -3.66076117e+02,  7.72501661e+00,  3.66076117e+00,
         6.14000000e+00,  6.64893521e+02,  6.02585284e+02,
         3.55557900e+00,  1.08808835e+03,  8.72853092e+00,
        -5.15326846e-01, -2.27342650e+02,  3.04200000e+01]])

In [219]:
X.shape[0]

1600

In [220]:
# premiere colonne de X (X0)
X[:,0]
# deuxieme colonne de X (hands right=0 left=1)
X[:,1]
# troisieme colonne de X (Arithmacy)
X[:,2]

array([58384., 67239., 23702., ..., 63905., 82713., 48639.])

### Definir Y

In [221]:
y_raw = list(data_train['Hogwarts House'])
s = set(y_raw)
s

{'Gryffindor', 'Hufflepuff', 'Ravenclaw', 'Slytherin'}

In [222]:
y = np.array([ord(a[0]) for a in y_raw])
y[:10]

array([82, 83, 82, 71, 71, 83, 71, 72, 71, 72])

In [223]:
y_Gry = np.array([1.0 if el == 'Gryffindor' else 0.0 for el in y_raw ])
y_Huf = np.array([1.0 if el == 'Hufflepuff' else 0.0 for el in y_raw ])
y_Rav = np.array([1.0 if el == 'Ravenclaw' else 0.0 for el in y_raw ])
y_Sly = np.array([1.0 if el == 'Slytherin' else 0.0 for el in y_raw ])

In [224]:
y_Gry.shape, y_Huf.shape, y_Rav.shape, y_Sly.shape

((1600,), (1600,), (1600,), (1600,))

In [225]:
Y = []
for name in s :  
    Y.append([1.0 if el == name else 0.0 for el in y_raw ])
Y = np.array(Y)
Y

array([[0., 0., 0., ..., 0., 1., 1.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [226]:
Y = Y.T

In [227]:
Y.shape

(1600, 4)

### Definir Theta


In [228]:
theta = np.zeros(15)
#theta = np.array([0.1,0.1,0.1,0.1,0.1,0.2,0.3,0.1,0.1,0.2,0.3,0.1,0.1,0.2,0.1])

In [229]:
X.shape, Y.shape, theta.shape

((1600, 15), (1600, 4), (15,))

In [230]:
X.shape[0]

1600

In [231]:
type(X), type(y), type(theta)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Model logistic :  Hypothese sigmoidale

In [232]:
def hipothesis_linear(X, theta):
    #return theta[0] + theta[1] * X
    return np.dot(X, theta)

In [233]:
# test hipothesis
h = hipothesis_linear(X[:,0:2], theta[0:2])
h.shape
set(h)
h[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [234]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

def hipothesis_log(X, theta):  
    return sigmoid(-np.dot(X, theta))
# returns a 100 x 1 matrix

In [235]:
# test sigmoid
sigmoid(0)

0.5

In [236]:
# test hipothesis
h = hipothesis_log(X[:,0:15], theta[0:15])
h.shape

(1600,)

### Tester la fonction du cout logistique

In [237]:
def cost_linear(X, y, theta):
    m = X.shape[0]
    print("m=", m)
    loss = hipothesis_linear(X, theta) - y
    print("loss=", loss)
    print('loss shape=', loss.shape)
    print("loss values=", set(loss))
    #mean_loss = np.sum((loss ** 2) ** 0.5)/ m
    #print("mean_loss=", mean_loss)
    loss2 = loss ** 2
    print("loss2=", loss2)
    print('loss shape=', loss2.shape)
    c = np.sum(loss2)
    print("c=" , c)
    cost = (np.sum(loss ** 2)) / (2 * m) 
    print("cost", cost)
    return cost

In [238]:
cost_linear(X[:,0:15], y_Gry, theta[0:15])

m= 1600
loss= [ 0.  0.  0. ... -1.  0.  0.]
loss shape= (1600,)
loss values= {0.0, -1.0}
loss2= [0. 0. 0. ... 1. 0. 0.]
loss shape= (1600,)
c= 327.0
cost 0.1021875


0.1021875

In [239]:

def cost_logistic(X, y, theta):
    m = X.shape[0]
    h = hipothesis_log(X, theta)
    cost = -(np.dot(y.T, np.log(h)) + np.dot((1-y).T, np.log(1-h)))/m
    return cost

In [243]:
cost_logistic(X[:,0:7], y_Gry, theta[0:7])

0.6931471805599455

In [37]:
def vusualize_cost(J_history) :
    %matplotlib inline
    fig = plt.figure()
    ax = plt.axes()
    ax.plot(J_history)
