In [1]:
import numpy as np
import pandas as pd
from pprint import pprint
import math

In [2]:
data_train = pd.read_csv("resources/dataset_train.csv")
#data_test = pd.read_csv("resources/dataset_test.csv")

In [3]:
data_train.head(10)

Index Hogwarts House First Name   Last Name    Birthday Best Hand  \
0      0      Ravenclaw     Tamara         Hsu  2000-03-30      Left   
1      1      Slytherin      Erich     Paredes  1999-10-14     Right   
2      2      Ravenclaw   Stephany       Braun  1999-11-03      Left   
3      3     Gryffindor      Vesta   Mcmichael  2000-08-19      Left   
4      4     Gryffindor     Gaston       Gibbs  1998-09-27      Left   
5      5      Slytherin    Corrine     Hammond  1999-04-04     Right   
6      6     Gryffindor        Tom       Guido  2000-09-30      Left   
7      7     Hufflepuff     Alicia     Hayward  1997-07-08     Right   
8      8     Gryffindor      Bella  Leatherman  1998-12-07      Left   
9      9     Hufflepuff     Hayden      Aponte  2001-10-13     Right   

   Arithmancy   Astronomy  Herbology  Defense Against the Dark Arts  \
0     58384.0 -487.886086   5.727180                       4.878861   
1     67239.0 -552.060507  -5.987446                       5.520605   
2     23702.0 -366.076117   7.725017                       3.660761   
3     32667.0  697.742809  -6.497214                      -6.977428   
4     60158.0  436.775204  -7.820623                            NaN   
5     21209.0 -613.687160  -4.289197                       6.136872   
6     49167.0  628.046051  -4.861976                      -6.280461   
7     33010.0  411.412727   5.931832                      -4.114127   
8     20278.0  496.394945  -5.215891                      -4.963949   
9     46316.0  527.193585   7.922205                      -5.271936   

   Divination  Muggle Studies  Ancient Runes  History of Magic  \
0       4.722      272.035831     532.484226          5.231058   
1      -5.612     -487.340557     367.760303          4.107170   
2       6.140      664.893521     602.585284          3.555579   
3       4.026     -537.001128     523.982133         -4.809637   
4       2.236     -444.262537     599.324514         -3.444377   
5      -6.592     -440.997704     396.201804          5.380286   
6         NaN     -926.892512     583.742442         -7.322486   
7       2.769     -502.021336     439.351416               NaN   
8       5.855     -626.552041     567.842402         -6.198661   
9       3.356     -398.101991     341.475606          4.978614   

   Transfiguration    Potions  Care of Magical Creatures     Charms  Flying  
0      1039.788281   3.790369                   0.715939 -232.79405  -26.89  
1      1058.944592   7.248742                   0.091674 -252.18425 -113.45  
2      1088.088348   8.728531                  -0.515327 -227.34265   30.42  
3       920.391449   0.821911                  -0.014040 -256.84675  200.64  
4       937.434724   4.311066                  -0.264070 -256.38730  157.98  
5      1052.845164  11.751212                   1.049894 -247.94549  -34.69  
6       923.539573   1.646666                   0.153022 -257.83447  261.55  
7      1041.091935   6.581791                  -0.171704 -244.03492   72.25  
8       925.255500   1.086518                   1.147032 -252.27561  244.11  
9      1041.414665   2.068824                  -0.529579 -244.57527   -0.09

In [4]:
column_names_list = list(data_train.columns)
column_names_list

['Index',
 'Hogwarts House',
 'First Name',
 'Last Name',
 'Birthday',
 'Best Hand',
 'Arithmancy',
 'Astronomy',
 'Herbology',
 'Defense Against the Dark Arts',
 'Divination',
 'Muggle Studies',
 'Ancient Runes',
 'History of Magic',
 'Transfiguration',
 'Potions',
 'Care of Magical Creatures',
 'Charms',
 'Flying']

In [9]:
m = data_train['Index'].shape[0]
m
type(m)

int

In [43]:
# Add a column of ones in X
X0 = np.ones(m)
X0[:10]
X0.shape

(1600,)

In [44]:
X1 = list(data_train['Best Hand'])
X1 = [0.0 if el == 'Left' else 1.0 for el in X1 ]
X1 = np.array(X1)
X1[:10]

array([0., 1., 0., 0., 0., 1., 0., 1., 0., 1.])

In [23]:
X2_15 = data_train[column_names_list[6:19]]
X2_15[:10]

Arithmancy   Astronomy  Herbology  Defense Against the Dark Arts  \
0     58384.0 -487.886086   5.727180                       4.878861   
1     67239.0 -552.060507  -5.987446                       5.520605   
2     23702.0 -366.076117   7.725017                       3.660761   
3     32667.0  697.742809  -6.497214                      -6.977428   
4     60158.0  436.775204  -7.820623                            NaN   
5     21209.0 -613.687160  -4.289197                       6.136872   
6     49167.0  628.046051  -4.861976                      -6.280461   
7     33010.0  411.412727   5.931832                      -4.114127   
8     20278.0  496.394945  -5.215891                      -4.963949   
9     46316.0  527.193585   7.922205                      -5.271936   

   Divination  Muggle Studies  Ancient Runes  History of Magic  \
0       4.722      272.035831     532.484226          5.231058   
1      -5.612     -487.340557     367.760303          4.107170   
2       6.140      664.893521     602.585284          3.555579   
3       4.026     -537.001128     523.982133         -4.809637   
4       2.236     -444.262537     599.324514         -3.444377   
5      -6.592     -440.997704     396.201804          5.380286   
6         NaN     -926.892512     583.742442         -7.322486   
7       2.769     -502.021336     439.351416               NaN   
8       5.855     -626.552041     567.842402         -6.198661   
9       3.356     -398.101991     341.475606          4.978614   

   Transfiguration    Potions  Care of Magical Creatures     Charms  Flying  
0      1039.788281   3.790369                   0.715939 -232.79405  -26.89  
1      1058.944592   7.248742                   0.091674 -252.18425 -113.45  
2      1088.088348   8.728531                  -0.515327 -227.34265   30.42  
3       920.391449   0.821911                  -0.014040 -256.84675  200.64  
4       937.434724   4.311066                  -0.264070 -256.38730  157.98  
5      1052.845164  11.751212                   1.049894 -247.94549  -34.69  
6       923.539573   1.646666                   0.153022 -257.83447  261.55  
7      1041.091935   6.581791                  -0.171704 -244.03492   72.25  
8       925.255500   1.086518                   1.147032 -252.27561  244.11  
9      1041.414665   2.068824                  -0.529579 -244.57527   -0.09

In [24]:
X2_15 = np.array(data_train[column_names_list[6:19]])
X2_15[:10]

array([[ 5.83840000e+04, -4.87886086e+02,  5.72718030e+00,
         4.87886086e+00,  4.72200000e+00,  2.72035831e+02,
         5.32484226e+02,  5.23105829e+00,  1.03978828e+03,
         3.79036907e+00,  7.15939127e-01, -2.32794050e+02,
        -2.68900000e+01],
       [ 6.72390000e+04, -5.52060507e+02, -5.98744578e+00,
         5.52060507e+00, -5.61200000e+00, -4.87340557e+02,
         3.67760303e+02,  4.10717029e+00,  1.05894459e+03,
         7.24874198e+00,  9.16741839e-02, -2.52184250e+02,
        -1.13450000e+02],
       [ 2.37020000e+04, -3.66076117e+02,  7.72501661e+00,
         3.66076117e+00,  6.14000000e+00,  6.64893521e+02,
         6.02585284e+02,  3.55557900e+00,  1.08808835e+03,
         8.72853092e+00, -5.15326846e-01, -2.27342650e+02,
         3.04200000e+01],
       [ 3.26670000e+04,  6.97742809e+02, -6.49721444e+00,
        -6.97742809e+00,  4.02600000e+00, -5.37001128e+02,
         5.23982133e+02, -4.80963661e+00,  9.20391449e+02,
         8.21910501e-01, -1.40404172e

In [40]:
X = X =np.c_[X0, X1, X2_15]
X[:3]

array([[ 1.00000000e+00,  0.00000000e+00,  5.83840000e+04,
        -4.87886086e+02,  5.72718030e+00,  4.87886086e+00,
         4.72200000e+00,  2.72035831e+02,  5.32484226e+02,
         5.23105829e+00,  1.03978828e+03,  3.79036907e+00,
         7.15939127e-01, -2.32794050e+02, -2.68900000e+01],
       [ 1.00000000e+00,  1.00000000e+00,  6.72390000e+04,
        -5.52060507e+02, -5.98744578e+00,  5.52060507e+00,
        -5.61200000e+00, -4.87340557e+02,  3.67760303e+02,
         4.10717029e+00,  1.05894459e+03,  7.24874198e+00,
         9.16741839e-02, -2.52184250e+02, -1.13450000e+02],
       [ 1.00000000e+00,  0.00000000e+00,  2.37020000e+04,
        -3.66076117e+02,  7.72501661e+00,  3.66076117e+00,
         6.14000000e+00,  6.64893521e+02,  6.02585284e+02,
         3.55557900e+00,  1.08808835e+03,  8.72853092e+00,
        -5.15326846e-01, -2.27342650e+02,  3.04200000e+01]])

In [38]:
y = list(data_train[column_names_list[1]])
y = [a[0] for a in y]
y = np.array(y)
y[:10]

array(['R', 'S', 'R', 'G', 'G', 'S', 'G', 'H', 'G', 'H'], dtype='<U1')

In [37]:
X.shape, y.shape

((1600, 15), (1600,))

In [41]:
type(X), type(y)

(numpy.ndarray, numpy.ndarray)